mindmap
  root((INCUMBÊNCIAS DO PODER PÚBLICO<br>PARA ASSEGURAR O DIREITO AO MEIO AMBIENTE))
    Preservar e restaurar os processos ecológicos essenciais
    Prover o manejo ecológico das espécies e ecossistemas
    Preservar a diversidade e a integridade do patrimônio genético do País
    Fiscalizar as entidades dedicadas à pesquisa e manipulação de material genético
    Definir, em todas as unidades da Federação, espaços territoriais a serem especialmente protegidos
    Exigir estudo prévio de impacto ambiental
    Controlar a produção, comercialização e emprego de técnicas, métodos e substâncias que comportem risco
    Promover a educação ambiental em todos os níveis de ensino e a conscientização pública
    Proteger a fauna e a flora
    Manter regime fiscal favorecido para os biocombustíveis e hidrogênio de baixa emissão
